In [32]:
import xgboost as xgb
from sklearn.preprocessing import LabelEncoder 
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
import numpy as np
from sklearn.metrics import confusion_matrix,ConfusionMatrixDisplay,multilabel_confusion_matrix,precision_recall_fscore_support
from sklearn.metrics import classification_report
import matplotlib.pyplot as plt
import pickle
import pandas as pd
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import GridSearchCV
import os

In [33]:
os.getcwd()

'/projectnb2/cs505/students/lseoane/malawi_news_classification/utils'

In [53]:
final_arr1 = np.load(f'/projectnb2/cs505/students/lseoane/malawi_news_classification/data/'+'eng_and_chich_split_texts' '.npy')
# final_arr2 = np.load(f'/projectnb2/cs505/students/lseoane/malawi_news_classification/data/'+'embeddings_chichewa' '.npy')
# print(final_arr1.shape)
# print(final_arr2.shape)
# final_arr=np.hstack([final_arr1,final_arr2])
final_arr=final_arr1

labels=pd.read_csv(f'/projectnb2/cs505/students/lseoane/malawi_news_classification/data/'+'eng_and_chich_split_labels'+'.csv')
target_names=labels['Label'].unique().astype(str).tolist()
labels=labels['Label'].values

idx=pd.read_csv(f'/projectnb2/cs505/students/lseoane/malawi_news_classification/data/'+'eng_and_chich_split_index'+'.csv')
idx=idx['Idx'].values


In [54]:
print(target_names)

['POLITICS', 'HEALTH', 'LAW/ORDER', 'RELIGION', 'FARMING', 'WILDLIFE/ENVIRONMENT', 'SOCIAL ISSUES', 'SOCIAL', 'OPINION/ESSAY', 'LOCALCHIEFS', 'WITCHCRAFT', 'ECONOMY', 'SPORTS', 'RELATIONSHIPS', 'TRANSPORT', 'CULTURE', 'EDUCATION', 'MUSIC', 'ARTS AND CRAFTS', 'FLOODING']


In [55]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(target_names)

f_target_names=le.transform(target_names)
labels=le.transform(labels)

In [56]:
print(set(labels))

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19}


In [57]:
print(f_target_names)

[11  6  7 13  4 18 15 14 10  8 19  2 16 12 17  1  3  9  0  5]


In [58]:
f_target_names=f_target_names.astype(str)

In [59]:
len(final_arr)

8541

In [60]:
xgb_model = XGBClassifier() 
lgr_model= LogisticRegression(random_state=np.random.seed(42))
rand_forest = RandomForestClassifier(random_state=np.random.seed(42))

X=final_arr
y=labels

skf = StratifiedKFold(n_splits=3)
skf.get_n_splits(X,y)


for train_index, test_index in skf.split(X, y):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    lgr_model=lgr_model.fit(X_train, y_train)
    rand_forest.fit(X_train, y_train)
    xgb_model.fit(X_train, y_train)
    
    
    y_pred = xgb_model.predict(X_test) 
    predictions = [value for value in y_pred]
    accuracy = accuracy_score(y_test,predictions) 
    print('xgb',accuracy)
    clf_r=classification_report(y_test,predictions,target_names=f_target_names)
    print('xgb',clf_r)
#     cm=multilabel_confusion_matrix(y_test,predictions)
#     print('xgb',cm)
    
    
    y_pred = lgr_model.predict(X_test) 
    predictions = [value for value in y_pred]
    accuracy = accuracy_score(y_test, predictions) 
    print('lgr',accuracy)
    clf_r=classification_report(y_test,predictions,target_names=f_target_names)
    print('lgr',clf_r)
#     cm=multilabel_confusion_matrix(y_test,predictions)
#     print('lgr',cm)

    y_pred = rand_forest.predict(X_test) 
    predictions = [value for value in y_pred]
    accuracy = accuracy_score(y_test, predictions) 
    print('RF',accuracy)
    clf_r=classification_report(y_test,predictions,target_names=f_target_names)
    print('RF',clf_r)
#     cm=multilabel_confusion_matrix(y_test,predictions)
#     print('RF',cm)


/share/pkg.7/python3/3.8.6/install/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


xgb 0.4179838426413769
xgb               precision    recall  f1-score   support

          11       0.57      0.24      0.33        17
           6       0.18      0.04      0.06        77
           7       0.21      0.21      0.21       188
          13       0.39      0.25      0.30        68
           4       0.51      0.45      0.47       191
          18       0.00      0.00      0.00        15
          15       0.42      0.28      0.34       193
          14       0.35      0.30      0.32       248
          10       0.56      0.13      0.21        70
           8       0.27      0.13      0.18        46
          19       0.00      0.00      0.00        74
           2       0.44      0.73      0.55       600
          16       0.64      0.69      0.66       152
          12       0.55      0.50      0.52       170
          17       0.30      0.25      0.27       134
           1       0.35      0.47      0.40       375
           3       0.77      0.51      0.62       109


/share/pkg.7/python3/3.8.6/install/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/share/pkg.7/python3/3.8.6/install/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/share/pkg.7/python3/3.8.6/install/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/prepr

xgb 0.42992623814541625
xgb               precision    recall  f1-score   support

          11       0.00      0.00      0.00        17
           6       0.38      0.10      0.16        78
           7       0.23      0.16      0.19       187
          13       0.57      0.19      0.29        68
           4       0.53      0.48      0.51       190
          18       0.00      0.00      0.00        16
          15       0.39      0.31      0.34       194
          14       0.35      0.29      0.31       248
          10       0.29      0.08      0.13        71
           8       0.43      0.20      0.27        45
          19       0.00      0.00      0.00        73
           2       0.45      0.75      0.56       599
          16       0.71      0.72      0.71       152
          12       0.53      0.45      0.49       170
          17       0.33      0.24      0.28       135
           1       0.32      0.49      0.39       374
           3       0.79      0.75      0.77       110

/share/pkg.7/python3/3.8.6/install/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/share/pkg.7/python3/3.8.6/install/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/share/pkg.7/python3/3.8.6/install/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/prepr

xgb 0.42887249736564803
xgb               precision    recall  f1-score   support

          11       1.00      0.35      0.52        17
           6       0.32      0.16      0.21        77
           7       0.20      0.13      0.16       188
          13       0.50      0.13      0.21        69
           4       0.50      0.62      0.56       190
          18       0.00      0.00      0.00        16
          15       0.43      0.30      0.35       194
          14       0.42      0.38      0.40       247
          10       0.35      0.09      0.14        70
           8       0.00      0.00      0.00        45
          19       0.00      0.00      0.00        73
           2       0.44      0.77      0.56       599
          16       0.62      0.65      0.64       152
          12       0.47      0.32      0.38       171
          17       0.44      0.19      0.27       135
           1       0.33      0.48      0.39       375
           3       0.77      0.63      0.69       110

/share/pkg.7/python3/3.8.6/install/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/share/pkg.7/python3/3.8.6/install/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [61]:
y_pred=[]
for i in range(0,len(final_arr)):
    y_pred.append(lgr_model.predict([final_arr[i]]))

In [62]:
y_preds=pd.DataFrame(y_pred,columns=['preds'])

In [63]:
y_preds['preds'].unique()

array([15,  3, 11,  9,  4,  6, 13,  7,  2, 18, 14, 16, 12,  8,  1, 10])

In [64]:
from sklearn import preprocessing
final_df=pd.DataFrame(columns=['Preds','Labels','Indexes'])
final_df['Preds']=y_preds['preds'].values
le = preprocessing.LabelEncoder()
le.fit(f_target_names)

f_target_names=le.transform(f_target_names)
labels=le.transform(labels)
preds=le.transform(y_preds['preds'])
final_df['Labels']=labels
final_df['Preds']=preds
final_df['Indexes']=idx.astype(int)

In [65]:
print(labels)

[3 3 3 ... 3 3 3]


In [66]:
a=final_df.groupby('Indexes')['Preds'].value_counts()

In [67]:
a

Indexes  Preds
0        3         3
         7         2
         19        2
         13        1
         14        1
                  ..
1434     7         3
         8         2
         19        2
         4         1
1435     3        11
Name: Preds, Length: 3340, dtype: int64

In [68]:
fin_labels=final_df.groupby('Indexes')['Labels'].mean().reset_index()

In [69]:
fin_labels

Indexes  Labels
0           0       3
1           1       3
2           2      16
3           3       3
4           4      17
...       ...     ...
1431     1431       9
1432     1432       3
1433     1433      13
1434     1434       7
1435     1435       3

[1436 rows x 2 columns]

In [70]:
final_preds=[]
for i in range(0,1435):
    final_preds.append(a[i].idxmax())


In [71]:
final_preds.append(0)

In [72]:
fin_labels['Labels'].values

array([ 3,  3, 16, ..., 13,  7,  3])

In [73]:
accuracy = accuracy_score(fin_labels['Labels'],final_preds) 
print(accuracy)

0.5167130919220055


In [75]:
b=classification_report(fin_labels['Labels'],final_preds,target_names=target_names)

In [76]:
print(b)

                      precision    recall  f1-score   support

            POLITICS       0.00      0.00      0.00         7
              HEALTH       0.00      0.00      0.00        23
           LAW/ORDER       0.00      0.00      0.00        26
            RELIGION       0.41      0.91      0.57       279
             FARMING       0.83      0.97      0.89        39
WILDLIFE/ENVIRONMENT       0.59      0.67      0.63       147
       SOCIAL ISSUES       0.52      0.16      0.24       152
              SOCIAL       0.46      0.59      0.52       134
       OPINION/ESSAY       0.91      0.82      0.86        49
         LOCALCHIEFS       0.00      0.00      0.00        11
          WITCHCRAFT       1.00      0.03      0.05        36
             ECONOMY       0.00      0.00      0.00        16
              SPORTS       0.47      0.27      0.34        86
       RELATIONSHIPS       0.65      0.30      0.41        43
           TRANSPORT       0.65      0.68      0.67        78
       