In [1]:
import os
import csv
import json
import logging
import math
from typing import List, Dict, Tuple, Callable, Iterable, Optional, Any

import torch
import torch.nn as nn
import pandas as pd
import pickle
import numpy as np
from keras.utils import np_utils
from sklearn.preprocessing import LabelEncoder
from numpy import save
from sklearn.metrics import accuracy_score, f1_score
from sklearn.metrics import classification_report

import tensorflow as tf

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation, BatchNormalization

from sklearn.model_selection import train_test_split

In [2]:
from google.colab import drive
drive.mount('/content/drive')
folder_ = 'drive/MyDrive/Masters/Year_1/Semester_2/CS_505/Project/'

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
!pip install transformers
!pip install sentence_transformers

In [4]:
from sentence_transformers import SentenceTransformer, models, InputExample, losses
from sentence_transformers.evaluation import LabelAccuracyEvaluator, SentenceEvaluator
from sentence_transformers.util import batch_to_device
from torch import Tensor
from torch.utils.data import DataLoader
from transformers import MT5EncoderModel, AutoConfig,T5Tokenizer
from transformers import pipeline, AutoTokenizer

In [5]:
train_df=pd.read_csv(folder_ + 'Data/Train.csv')
train_df_english=pd.read_csv(folder_ + 'Data/train_google_translated.csv')

#test_df=pd.read_csv('C:/Users/leose/second_semester/NLP/malawi_news_classification/data/test.csv')

In [6]:
train_df['Text']=train_df['Text'].tolist()
train_df_english['Text']=train_df_english['Text'].tolist()
#test_df['Text']=test_df['Text'].tolist()
#test_batch_sentences=[]

#for frame in train_df['Text']:
#    train_batch_sentences.append(frame)
#for sentence in test_df['Text']:
#    test_batch_sentences.append(frame)

In [8]:
print(len(train_df))
print(len(train_df_english))

1436
1436


In [7]:
model = MT5EncoderModel.from_pretrained("google/mt5-small")
tokenizer = T5Tokenizer.from_pretrained("google/mt5-small")
#article = "UN Offizier sagt, dass weiter verhandelt werden muss in Syrien."
#for sentence
#input_ids = tokenizer(train_batch_sentences[0], return_tensors="pt",truncation=True,max_length=512).input_ids
#outputs = model(input_ids)
#hidden_state = outputs.last_hidden_state

Some weights of the model checkpoint at google/mt5-small were not used when initializing MT5EncoderModel: ['decoder.block.1.layer.2.layer_norm.weight', 'decoder.block.5.layer.2.DenseReluDense.wo.weight', 'decoder.block.4.layer.2.DenseReluDense.wi_1.weight', 'decoder.block.0.layer.2.DenseReluDense.wo.weight', 'decoder.block.1.layer.0.SelfAttention.q.weight', 'decoder.block.1.layer.0.SelfAttention.v.weight', 'decoder.block.4.layer.1.EncDecAttention.v.weight', 'decoder.block.1.layer.1.EncDecAttention.v.weight', 'decoder.block.7.layer.0.SelfAttention.v.weight', 'decoder.block.3.layer.1.EncDecAttention.k.weight', 'decoder.block.0.layer.2.DenseReluDense.wi_0.weight', 'decoder.final_layer_norm.weight', 'decoder.block.5.layer.0.layer_norm.weight', 'decoder.block.7.layer.1.EncDecAttention.q.weight', 'decoder.block.1.layer.1.layer_norm.weight', 'decoder.block.2.layer.2.DenseReluDense.wi_1.weight', 'decoder.block.4.layer.2.DenseReluDense.wo.weight', 'decoder.block.6.layer.1.EncDecAttention.q.weig

In [ ]:
'''
input_ids = []
#for frame in train_df['Text'][:400]:
lower = 1200
#upper = lower+400
upper = len(train_df)
for frame in train_df['Text'][lower:upper]:
    input_ids.append(tokenizer(frame, return_tensors="pt",truncation=True,max_length=64).input_ids)

outputs = []
for input_ in input_ids:
  outputs.append(model(input_))

hidden_state = []
for output_ in outputs:
  hidden_state.append(output_.last_hidden_state)

values = torch.zeros((400,512))
for i in range(len(hidden_state)):
  values[i] = (torch.mean(hidden_state[i][0],axis=0))

#save(folder_ + 'Data/' + 'data_400_800.npy', values.detach().numpy())

save(folder_ + 'Data/' + 'data_' + str(lower) + '_' + str(upper) + '.npy', values.detach().numpy())
'''

In [9]:
'''
input_ids = []
#for frame in train_df['Text'][:400]:
lower = 1200
#upper = lower+300
upper = len(train_df)
for frame in train_df_english['Text'][lower:upper]:
    input_ids.append(tokenizer(frame, return_tensors="pt",truncation=True,max_length=64).input_ids)

outputs = []
for input_ in input_ids:
  outputs.append(model(input_))

hidden_state = []
for output_ in outputs:
  hidden_state.append(output_.last_hidden_state)

values = torch.zeros((300,512))
for i in range(len(hidden_state)):
  values[i] = (torch.mean(hidden_state[i][0],axis=0))

#save(folder_ + 'Data/' + 'data_400_800.npy', values.detach().numpy())

save(folder_ + 'Data/' + 'data_' + str(lower) + '_' + str(upper) + '_english.npy', values.detach().numpy())
'''

In [ ]:
li[3][236]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [7]:
lower = 0
upper = lower+400
li = []
for i in range(4):
  arr = np.load(folder_ + 'Data/' + 'data_' + str(lower) + '_' + str(upper) + '.npy')
  li.append(arr)
  lower+=400
  upper+=400
  if(lower == 1200):
    upper = 1436
  #break

In [8]:
final_arr = np.vstack((li[0],li[1],li[2],li[3]))
final_arr = final_arr[:1436]

In [9]:
final_arr.shape

(1436, 512)

In [10]:
final_arr[1435]

array([-5.26638143e-02, -1.54549867e-01,  1.86291840e-02, -1.83572739e-01,
       -7.87804574e-02,  5.09037301e-02,  2.03488126e-01,  3.10577769e-02,
       -2.82362122e-02, -4.99501117e-02,  2.41595507e-01, -1.40947133e-01,
        3.49488258e-02, -1.30859837e-01,  6.62851632e-02, -8.03611204e-02,
       -1.00439146e-01, -3.87492739e-02, -8.31745118e-02,  6.70289844e-02,
        2.66414620e-02,  1.25922114e-01, -8.44994038e-02,  5.71737066e-02,
       -3.76449794e-01,  2.24952493e-02, -8.02223682e-01,  2.64139920e-02,
        9.43697542e-02,  1.39501467e-01,  6.02034554e-02,  9.61242914e-02,
       -1.40072122e-01, -8.43710750e-02,  2.26025637e-02,  8.08138996e-02,
       -6.60696030e-02,  1.28506556e-01,  3.32188196e-02, -2.54327714e-01,
        1.76303789e-01, -9.96564031e-02, -1.18747167e-01,  9.18802321e-02,
        9.74093527e-02, -1.41530484e-01,  8.24178755e-02, -1.24160178e-01,
        5.84548041e-02, -2.65140980e-02, -1.03624135e-01, -2.03897849e-01,
       -2.53316015e-02,  

In [11]:
lower = 0
upper = lower+300
li = []
for i in range(5):
  arr_english = np.load(folder_ + 'Data/' + 'data_' + str(lower) + '_' + str(upper) + '_english.npy')
  li.append(arr_english)
  lower+=300
  upper+=300
  if(lower == 1200):
    upper = 1436
  #break

In [12]:
len(li)

5

In [13]:
final_arr_english = np.vstack((li[0],li[1],li[2],li[3],li[4]))
final_arr_english = final_arr_english[:1436]

In [14]:
final_arr_english.shape

(1436, 512)

In [15]:
final_arr_english[1435]

array([-6.14335388e-03, -1.90163970e-01, -7.79935271e-02, -5.37078232e-02,
       -1.34949416e-01,  8.67662057e-02,  1.90029353e-01,  9.86115262e-03,
       -9.85435396e-02, -2.05613688e-01,  2.08218664e-01, -2.84024663e-02,
       -2.41926871e-03, -7.43922740e-02,  1.97681084e-01, -2.58285757e-02,
        2.02874959e-01, -5.60942814e-02, -5.10451198e-02,  1.78223088e-01,
        1.00612864e-01,  1.66835755e-01, -8.99607316e-03,  5.08847833e-02,
       -2.06167102e-02,  1.11117968e-02, -7.96199322e-01, -1.24473333e-01,
       -2.43776798e-01,  2.05756411e-01,  2.60200873e-02,  3.94259430e-02,
       -1.42344171e-02, -1.51687041e-02, -6.54334947e-02, -1.68005362e-01,
       -8.85375738e-02,  2.33345315e-01,  2.74571210e-01, -1.83020294e-01,
        1.27800360e-01, -4.90180254e-02,  1.82920266e-02,  2.11384982e-01,
        6.73183203e-02,  1.56480849e-01,  4.25525159e-02, -7.31685311e-02,
       -2.55722702e-02,  1.26586221e-02, -1.39706284e-01, -2.57001668e-01,
       -2.41024438e-02,  

In [16]:
final_comb_arr = np.hstack((final_arr,final_arr_english))

In [17]:
final_comb_arr.shape

(1436, 1024)

In [18]:
np.unique(train_df['Label']).shape[0]

20

In [19]:
le = LabelEncoder()
train_df.Label = le.fit_transform(train_df.Label)

In [20]:
Y_train = np_utils.to_categorical(train_df['Label'], np.unique(train_df['Label']).shape[0])

In [21]:
print(Y_train.shape)
print(Y_train[0])

(1436, 20)
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]


In [22]:
print('Building model...')
model = Sequential()
model.add(Dense(2048, input_shape=(1024,)))
model.add(Activation('relu'))
model.add(Dropout(0.2))
model.add(Dense(20))
model.add(Activation('softmax'))

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
#make one, takes in, double that amount, english and chichewa

Building model...


In [23]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 2048)              2099200   
                                                                 
 activation (Activation)     (None, 2048)              0         
                                                                 
 dropout (Dropout)           (None, 2048)              0         
                                                                 
 dense_1 (Dense)             (None, 20)                40980     
                                                                 
 activation_1 (Activation)   (None, 20)                0         
                                                                 
Total params: 2,140,180
Trainable params: 2,140,180
Non-trainable params: 0
_________________________________________________________________


In [24]:
X_train, X_test, y_train, y_test = train_test_split(
        final_comb_arr, Y_train, test_size=0.3, random_state=42, stratify=Y_train)

In [25]:
X_train.shape

(1005, 1024)

In [26]:
X_train[0]

array([ 0.02751722, -0.00119188, -0.05982733, ...,  0.194644  ,
        0.17343605, -0.28630933], dtype=float32)

In [27]:
y_train[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 0.], dtype=float32)

In [28]:
#train_dataset = tf.data.Dataset.from_tensor_slices((values.detach().numpy(), Y_train[:400]))
train_dataset = tf.data.Dataset.from_tensor_slices((X_train, y_train))

test_dataset = tf.data.Dataset.from_tensor_slices((X_test, y_test))

In [29]:
BATCH_SIZE = 32
SHUFFLE_BUFFER_SIZE = 100

train_dataset = train_dataset.shuffle(SHUFFLE_BUFFER_SIZE).batch(BATCH_SIZE)
test_dataset = test_dataset.batch(BATCH_SIZE)

In [30]:
result = model.fit(train_dataset,
                    epochs=100, batch_size=32,
                    verbose=1)

Epoch 1/100
32/32 [==============================] - 1s 12ms/step - loss: 2.3811 - accuracy: 0.2806
Epoch 2/100
32/32 [==============================] - 0s 11ms/step - loss: 1.8483 - accuracy: 0.4577
Epoch 3/100
32/32 [==============================] - 0s 12ms/step - loss: 1.6069 - accuracy: 0.5274
Epoch 4/100
32/32 [==============================] - 0s 13ms/step - loss: 1.4206 - accuracy: 0.5721
Epoch 5/100
32/32 [==============================] - 0s 12ms/step - loss: 1.2985 - accuracy: 0.6010
Epoch 6/100
32/32 [==============================] - 0s 12ms/step - loss: 1.1509 - accuracy: 0.6478
Epoch 7/100
32/32 [==============================] - 0s 12ms/step - loss: 1.0605 - accuracy: 0.6507
Epoch 8/100
32/32 [==============================] - 0s 12ms/step - loss: 0.9446 - accuracy: 0.7144
Epoch 9/100
32/32 [==============================] - 0s 12ms/step - loss: 0.8777 - accuracy: 0.7274
Epoch 10/100
32/32 [==============================] - 0s 14ms/step - loss: 0.8129 - accuracy: 0.7433

In [31]:
# 100 epochs
model.evaluate(test_dataset)

14/14 [==============================] - 0s 6ms/step - loss: 3.0351 - accuracy: 0.4687


[3.035072088241577, 0.46867749094963074]

In [32]:
ans = model.predict(test_dataset)

In [33]:
ans[0].shape

(20,)

In [34]:
y_test[0]

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.], dtype=float32)

In [35]:
print(accuracy_score(y_test, np_utils.to_categorical(np.argmax(ans,axis=1))))
print(classification_report(y_test, np_utils.to_categorical(np.argmax(ans,axis=1))),)

0.46867749419953597
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         2
           1       0.00      0.00      0.00         7
           2       0.27      0.15      0.20        26
           3       0.38      0.23      0.29        13
           4       0.52      0.70      0.59        23
           5       0.00      0.00      0.00         2
           6       0.57      0.45      0.50        38
           7       0.49      0.46      0.48        41
           8       0.25      0.14      0.18         7
           9       0.50      0.50      0.50         4
          10       0.00      0.00      0.00         8
          11       0.61      0.63      0.62        84
          12       0.82      0.75      0.78        12
          13       0.44      0.59      0.50        44
          14       0.31      0.33      0.32        46
          15       0.35      0.53      0.42        40
          16       0.71      0.67      0.69        15
       

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
np_utils.to_categorical(np.argmax(ans[:2],axis=1))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 1.]], dtype=float32)

In [ ]:
# 10 epochs
model.evaluate(test_dataset)

14/14 [==============================] - 0s 3ms/step - loss: 1.8786 - accuracy: 0.4130


[1.8785860538482666, 0.41299304366111755]

In [ ]:
result = model.fit(values, Y_train[:400],
                    epochs=2, batch_size=32,
                    verbose=1)

TypeError: ignored

https://austingwalters.com/classify-sentences-via-a-multilayer-perceptron-mlp/
https://github.com/holbertonschool/deep-learning/blob/master/Class%20%233/Text%20Classification%20MLP%20Reuters%20Dataset.ipynb
https://towardsdatascience.com/text-classification-with-extremely-small-datasets-333d322caee2


Hidden state (embeddings):
https://github.com/huggingface/transformers/issues/1950